version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: contato
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgrespassword@postgres:5432/contato?schema=public"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: web_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata: