FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY prisma ./prisma/
RUN npm install
COPY . .
RUN npx prisma generate
EXPOSE 3000

# Aplica as migrations e em seguida roda o seed do admin
CMD ["sh", "-c", "npx prisma migrate deploy && npm start"]